### ISSUE TITLE
运行test失败

### ISSUE THREAD

**Issue by ghost** [modianor/opencv-Java#1]
报错这个
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jniopencv_core in java.library.path，
但我已经把mvn项目的jar import了啊，是不是要下载库到什么别的地方

**Comment by modianor** [comment]
我能看下你的pom文件吗？



---原始邮件---
发件人: "kwbrb"<notifications@github.com&gt;
发送时间: 2020年4月23日(周四) 晚上6:41
收件人: "modianor/opencv-Java"<opencv-Java@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [modianor/opencv-Java] 运行test失败 (#1)




 
报错这个
 Exception in thread "main" java.lang.UnsatisfiedLinkError: no jniopencv_core in java.library.path，
 但我已经把mvn项目的jar import了啊，是不是要下载库到什么别的地方

**Comment by ghost** [comment]
> 我能看下你的pom文件吗？
> […](#)
> ---原始邮件--- 发件人: "kwbrb"<notifications@github.com&gt; 发送时间: 2020年4月23日(周四) 晚上6:41 收件人: "modianor/opencv-Java"<opencv-Java@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [modianor/opencv-Java] 运行test失败 (#1) 报错这个 Exception in thread "main" java.lang.UnsatisfiedLinkError: no jniopencv_core in java.library.path， 但我已经把mvn项目的jar import了啊，是不是要下载库到什么别的地方 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>opencvdemo</artifactId>
    <version>1.0-SNAPSHOT</version>
    <dependencies>
        <dependency>
            <groupId>org.bytedeco.javacpp-presets</groupId>
            <artifactId>opencv</artifactId>
            <version>3.4.3-1.4.3</version>
        </dependency>

        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-io</artifactId>
            <version>1.3.2</version>
        </dependency>
    </dependencies>

</project>

**Comment by ghost** [comment]
我应该是整个克隆下来的就是改了一下路径而已

**Comment by modianor** [comment]
添加一组依赖
<dependency&gt;         <groupId&gt;org.bytedeco.javacpp-presets</groupId&gt;         <artifactId&gt;opencv-platform</artifactId&gt;         <version&gt;3.4.3-1.4.3</version&gt;     </dependency&gt;



---原始邮件---
发件人: "kwbrb"<notifications@github.com&gt;
发送时间: 2020年4月23日(周四) 晚上6:48
收件人: "modianor/opencv-Java"<opencv-Java@noreply.github.com&gt;;
抄送: "modianor"<1138716463@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [modianor/opencv-Java] 运行test失败 (#1)




  
我能看下你的pom文件吗？
 …
 ---原始邮件--- 发件人: "kwbrb"<notifications@github.com&gt; 发送时间: 2020年4月23日(周四) 晚上6:41 收件人: "modianor/opencv-Java"<opencv-Java@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [modianor/opencv-Java] 运行test失败 (#1) 报错这个 Exception in thread "main" java.lang.UnsatisfiedLinkError: no jniopencv_core in java.library.path， 但我已经把mvn项目的jar import了啊，是不是要下载库到什么别的地方 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  

 4.0.0
 <groupId&gt;org.example</groupId&gt; <artifactId&gt;opencvdemo</artifactId&gt; <version&gt;1.0-SNAPSHOT</version&gt; <dependencies&gt;     <dependency&gt;         <groupId&gt;org.bytedeco.javacpp-presets</groupId&gt;         <artifactId&gt;opencv</artifactId&gt;         <version&gt;3.4.3-1.4.3</version&gt;     </dependency&gt;     <dependency&gt;         <groupId&gt;org.apache.commons</groupId&gt;         <artifactId&gt;commons-io</artifactId&gt;         <version&gt;1.3.2</version&gt;     </dependency&gt; </dependencies&gt;

**Comment by ghost** [comment]
> 添加一组依赖 <dependency&gt; <groupId&gt;org.bytedeco.javacpp-presets</groupId&gt; <artifactId&gt;opencv-platform</artifactId&gt; <version&gt;3.4.3-1.4.3</version&gt; </dependency&gt;
> […](#)
> ---原始邮件--- 发件人: "kwbrb"<notifications@github.com&gt; 发送时间: 2020年4月23日(周四) 晚上6:48 收件人: "modianor/opencv-Java"<opencv-Java@noreply.github.com&gt;; 抄送: "modianor"<1138716463@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题: Re: [modianor/opencv-Java] 运行test失败 (#1) 我能看下你的pom文件吗？ … ---原始邮件--- 发件人: "kwbrb"<notifications@github.com&gt; 发送时间: 2020年4月23日(周四) 晚上6:41 收件人: "modianor/opencv-Java"<opencv-Java@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [modianor/opencv-Java] 运行test失败 (#1) 报错这个 Exception in thread "main" java.lang.UnsatisfiedLinkError: no jniopencv_core in java.library.path， 但我已经把mvn项目的jar import了啊，是不是要下载库到什么别的地方 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 4.0.0 <groupId&gt;org.example</groupId&gt; <artifactId&gt;opencvdemo</artifactId&gt; <version&gt;1.0-SNAPSHOT</version&gt; <dependencies&gt; <dependency&gt; <groupId&gt;org.bytedeco.javacpp-presets</groupId&gt; <artifactId&gt;opencv</artifactId&gt; <version&gt;3.4.3-1.4.3</version&gt; </dependency&gt; <dependency&gt; <groupId&gt;org.apache.commons</groupId&gt; <artifactId&gt;commons-io</artifactId&gt; <version&gt;1.3.2</version&gt; </dependency&gt; </dependencies&gt; — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

把图片里面的数字识别出来的函数是哪个
方便加下qq吗

**Comment by modianor** [comment]
没有这样的函数 QQ：345563121



---原始邮件---
发件人: "kwbrb"<notifications@github.com&gt;
发送时间: 2020年4月23日(周四) 晚上6:55
收件人: "modianor/opencv-Java"<opencv-Java@noreply.github.com&gt;;
抄送: "modianor"<1138716463@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [modianor/opencv-Java] 运行test失败 (#1)




  
添加一组依赖 <dependency&gt; <groupId&gt;org.bytedeco.javacpp-presets</groupId&gt; <artifactId&gt;opencv-platform</artifactId&gt; <version&gt;3.4.3-1.4.3</version&gt; </dependency&gt;
 …
 ---原始邮件--- 发件人: "kwbrb"<notifications@github.com&gt; 发送时间: 2020年4月23日(周四) 晚上6:48 收件人: "modianor/opencv-Java"<opencv-Java@noreply.github.com&gt;; 抄送: "modianor"<1138716463@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题: Re: [modianor/opencv-Java] 运行test失败 (#1) 我能看下你的pom文件吗？ … ---原始邮件--- 发件人: "kwbrb"<notifications@github.com&gt; 发送时间: 2020年4月23日(周四) 晚上6:41 收件人: "modianor/opencv-Java"<opencv-Java@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [modianor/opencv-Java] 运行test失败 (#1) 报错这个 Exception in thread "main" java.lang.UnsatisfiedLinkError: no jniopencv_core in java.library.path， 但我已经把mvn项目的jar import了啊，是不是要下载库到什么别的地方 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 4.0.0 <groupId&gt;org.example</groupId&gt; <artifactId&gt;opencvdemo</artifactId&gt; <version&gt;1.0-SNAPSHOT</version&gt; <dependencies&gt; <dependency&gt; <groupId&gt;org.bytedeco.javacpp-presets</groupId&gt; <artifactId&gt;opencv</artifactId&gt; <version&gt;3.4.3-1.4.3</version&gt; </dependency&gt; <dependency&gt; <groupId&gt;org.apache.commons</groupId&gt; <artifactId&gt;commons-io</artifactId&gt; <version&gt;1.3.2</version&gt; </dependency&gt; </dependencies&gt; — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
  
把图片里面的数字识别出来的函数是哪个
 方便加下qq吗
